// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get

extension Paths {
    public static var login: Login {
        Login(path: "/login")
    }

    public struct Login {
        /// Path: `/login`
        public let path: String

        /// This endpoint logs in a client to the server, returning information about the user and server. The /api/authorize endpoint is also available if an API token was persisted.
        public func post(_ body: PostRequest) -> Request<AudiobookshelfKit.LibraryItem> {
            Request(path: path, method: "POST", body: body)
        }

        public struct PostRequest: Encodable {
            public var username: String
            public var password: String

            public init(username: String, password: String) {
                self.username = username
                self.password = password
            }

            public func encode(to encoder: Encoder) throws {
                var values = encoder.container(keyedBy: StringCodingKey.self)
                try values.encode(username, forKey: "username")
                try values.encode(password, forKey: "password")
            }
        }
    }
}
