// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct CollectionExpanded: Codable {
    /// The ID of the collection.
    public var id: String?
    /// The ID of the library the collection belongs to.
    public var libraryID: String?
    /// The ID of the user that created the collection.
    public var userID: String?
    /// The name of the collection.
    public var name: String?
    /// The name of the collection.
    public var description: String?
    /// The books that belong to the collection.
    public var books: [LibraryItemExpanded]?
    /// The time (in ms since POSIX epoch) when the collection was last updated.
    public var lastUpdate: Int?
    /// The time (in ms since POSIX epoch) when the collection was created.
    public var createdAt: Int?

    public init(id: String? = nil, libraryID: String? = nil, userID: String? = nil, name: String? = nil, description: String? = nil, books: [LibraryItemExpanded]? = nil, lastUpdate: Int? = nil, createdAt: Int? = nil) {
        self.id = id
        self.libraryID = libraryID
        self.userID = userID
        self.name = name
        self.description = description
        self.books = books
        self.lastUpdate = lastUpdate
        self.createdAt = createdAt
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.libraryID = try values.decodeIfPresent(String.self, forKey: "libraryId")
        self.userID = try values.decodeIfPresent(String.self, forKey: "userId")
        self.name = try values.decodeIfPresent(String.self, forKey: "name")
        self.description = try values.decodeIfPresent(String.self, forKey: "description")
        self.books = try values.decodeIfPresent([LibraryItemExpanded].self, forKey: "books")
        self.lastUpdate = try values.decodeIfPresent(Int.self, forKey: "lastUpdate")
        self.createdAt = try values.decodeIfPresent(Int.self, forKey: "createdAt")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(libraryID, forKey: "libraryId")
        try values.encodeIfPresent(userID, forKey: "userId")
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(description, forKey: "description")
        try values.encodeIfPresent(books, forKey: "books")
        try values.encodeIfPresent(lastUpdate, forKey: "lastUpdate")
        try values.encodeIfPresent(createdAt, forKey: "createdAt")
    }
}
