// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct PlaylistItem: Codable {
    /// The ID of the library item the playlist item is for.
    public var libraryItemID: String?
    /// The ID of the podcast episode the playlist item is for.
    public var episodeID: String?

    public init(libraryItemID: String? = nil, episodeID: String? = nil) {
        self.libraryItemID = libraryItemID
        self.episodeID = episodeID
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.libraryItemID = try values.decodeIfPresent(String.self, forKey: "libraryItemId")
        self.episodeID = try values.decodeIfPresent(String.self, forKey: "episodeId")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(libraryItemID, forKey: "libraryItemId")
        try values.encodeIfPresent(episodeID, forKey: "episodeId")
    }
}
