// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct PodcastFeed: Codable {
    public var metadata: PodcastMetadata?
    public var episodes: [PodcastEpisode]?

    public init(metadata: PodcastMetadata? = nil, episodes: [PodcastEpisode]? = nil) {
        self.metadata = metadata
        self.episodes = episodes
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.metadata = try values.decodeIfPresent(PodcastMetadata.self, forKey: "metadata")
        self.episodes = try values.decodeIfPresent([PodcastEpisode].self, forKey: "episodes")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(metadata, forKey: "metadata")
        try values.encodeIfPresent(episodes, forKey: "episodes")
    }
}
