// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct PodcastFeedMinified: Codable {
    public var metadata: PodcastMetadata?
    /// The number of episodes the podcast has.
    public var numEpisodes: Int?

    public init(metadata: PodcastMetadata? = nil, numEpisodes: Int? = nil) {
        self.metadata = metadata
        self.numEpisodes = numEpisodes
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.metadata = try values.decodeIfPresent(PodcastMetadata.self, forKey: "metadata")
        self.numEpisodes = try values.decodeIfPresent(Int.self, forKey: "numEpisodes")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(metadata, forKey: "metadata")
        try values.encodeIfPresent(numEpisodes, forKey: "numEpisodes")
    }
}
